bay/docker/hosts.py
bay/docker/runner.py
bay/utils/threading.py

In particular, trying to start the same container from two threads
separately now works (boot containers do this).

Make running/stopping containers more threadsafe.

---

bay/cli/__init__.py
bay/cli/tasks.py
bay/docker/build.py

This solves most of the weird output overwriting issues.

Change task rate-limiting to be an opt-in context decorator

---

bay/plugins/waits.py

Allows to wait on a file appearing, which allows containers to wait
until a build process or similar has finished during startup (initially
used for our Grunt process)

Add file-based wait

---

Makefile

It's not particularly exciting, but it handles tagging and pushing up releases to PyPI.

Add basic release Makefile

---

bay/plugins/profile.py

Dependency removal of containers was doing this.

Fix "tug up" to not remove containers after it's added them

---

bay/plugins/images.py
bay/plugins/volume.py

They're both now singular and have a separate "list"

Make volumes and images commands consistent

---

bay/containers/container.py
bay/containers/formation.py
bay/containers/profile.py

Also honours the "foreground" key when it's set for a test container

Use environment variables properly from profiles/containers

---

bay/containers/profile.py

A simple fix for something I overlooked last Friday.

Fix profiles when they do not get environment populated

---

bay/plugins/ps.py

This is much more useful information!

Make "bay ps" show ports rather than image hash

---

bay/containers/container.py
bay/docker/introspect.py
bay/docker/runner.py
bay/plugins/build_scripts.py
bay/plugins/ps.py

A few different improvements to help basic usability.

Fast kill, python build scripts, and improved `bay ps`

---

bay/containers/formation.py
bay/plugins/attach.py
bay/plugins/run.py

Improves `bay attach`, and `bay run` for both the container itself and linked dependencies.

Improve error messages for missing images

---

bay/plugins/run.py

You can still stop them with specific "bay stop ssh-agent"

Don't stop system containers in general "bay stop"

---

bay/plugins/ssh_agent.py

so we can eventually deprecate TUGBOAT_SSH_AUTH_HOST

Add support for SSH_AUTH_HOST

---

bay/containers/formation.py

This allows the process to continue working, rather than block the user if their project layout changes under them but they have a current profile from a slightly older version.

Change validation errors on devmodes, links to warnings

---

bay/docker/towline.py

It was using an older Docker API that stopped working, so this switches it to use the new one and to correctly understand the JSON output.
We should switch the paths and handling for this at some point soon to get rid of `tugboat`, too.

Fix towline reading so that it correctly looks for boot status

---

bay/plugins/mounts.py

`bay mounts` now lists containers that have devmodes, but aren't in the current profile

show potential mounts for all containers

---

bay/plugins/waits.py

We have had issues with containers repeatedly disconnecting while the HTTP wait check is running, resulting in `bay` waiting seemingly forever for the container to be available even though it is running.
The `HttpWait.ready` method now incorporates a sub-loop that handles `RemoteDisconnected` exceptions by immediately retrying the connection as many times as necessary to get a response.

Make HttpWait.ready() immediately retry on RemoteDisconnected exception

---

bay/plugins/build.py

Add volumes to `containers_to_pull` using a call to `dependency_sort`, so that we compute volumes for every container in the hierarchy rather than just the ones that are explicitly in the profile

Build volumes required by all ancestors of containers in the profile

---

bay/docker/hosts.py

we don't need to inspect the docker network settings to get the host IP anymore in the latest versions of Docker for Mac and Windows.
If we are on a recent version, use the built-in hostname. If not, fallback to the old code.

Fix error when the docker network doesn't exist

---

CHANGELOG.txt
bay/plugins/tail.py

Change the default number of lines to all.
Switch the number of lines from a parameter to an option.
Copied docker logs documentation.

Improve the tail plugin

---

bay/plugins/tail.py

support for `-n` option in `tail` command to make it consistent with UNIX `tail` command

support for `-n` option in `tail` command 

---

CHANGELOG.txt
bay/containers/container.py
bay/docker/runner.py
bay/version.py

for instance:
```
volumes:
"/tmp/test": "$HOME/my/folder"
```

Volume improvements

---

CHANGELOG.txt
bay/containers/profile.py
bay/version.py

it doesn't break anything and it is caused by profile changes

Remove profile container warning

---

bay/containers/graph.py
bay/containers/volumes.py

As per https://github.com/python-attrs/attrs/issues/307

[PATCH] Migrate `convert` to `converter`

---

CHANGELOG.txt
RELEASE.md
tasks.py

Add support for the invoke release flow.

[MINOR] Add support for invoke release
