bay/cli/__init__.py, bay/cli/tasks.py, bay/containers/container.py, bay/containers/formation.py, bay/containers/graph.py, bay/containers/profile.py, bay/docker/introspect.py, bay/docker/runner.py, bay/plugins/container.py, bay/plugins/mounts.py, bay/plugins/profile.py, bay/plugins/run.py
* Removes custom restart-containers code from tug mount and uses tug up instead
* Fixes tug up/stop to stop dependent containers first
* Unifies the threading code for runner into a single function
* Adds a new way of calling other commands that removes the need to pass the context along
* Make the reprs of some of the bigger objects more readable
* Moved devmount git resolution code alongside the volume git resolution code in Container
* Turned off default-boot for user profiles' container names, with deprecation path for it totally
* Made the introspector populate all parts of an instance
=> Fix tug mount and runtime resolution issues

bay/plugins/boot.py
This lets node have `sinopia` as an optional dependency
=> Don't error out for containers requiring themselves optionally to boot

bay/containers/profile.py
Otherwise it's impossible to change profile away from them.
=> Make user_profiles with vanished containers not fail super hard

bay/containers/formation.py, bay/plugins/run.py
This was because of removing containers' dependents.
=> Fix problem where a container was removed multiple times

bay/containers/formation.py, bay/docker/runner.py
Formation.remove_container will correctly try to remove all descendants,
but when the runner tries to restart a container it was not doing the
same. This changes the stop code so it always removes any running
descendants.
=> Prevent stop deadlocks when the container is merely being restarted

bay/containers/profile.py
Previously, when bay would apply the user profile after applying the parent profile, it would overwrite the port mapping from the parent profile with the port mapping in the user profile.
The fix is to merge the second profile ports onto the existing one, so only keys that are specified in the second profile are overwritten.
=> Applying multiple profiles to the same graph does not overwrite ports

bay/containers/profile.py
Don't include foreground containers in the default boot set.
=> Make `bay up` ignore foreground containers

bay/plugins/volume.py
I'm sure we'll see a few more of these, but this is triggered when running `volumes list` on a fresh Docker install.
=> Fix another case where docker returns None not []

bay/containers/graph.py, bay/containers/profile.py, bay/plugins/build.py
It was only building default-boot ones before, which meant it didn't build foreground containers.
=> Make `bay build profile` build everything specified in a profile file

.gitignore, .travis.yml, bay/plugins/ps.py, bay/utils/humanize.py, setup.cfg, setup.py, tests/test_humanize.py
It's optional because fetching memory usage takes about 1s per container
for some reason.
=> Add optional memory output to the "bay ps" command, and a test suite

bay/containers/container.py, bay/plugins/profile.py
This means we can mark containers that should not be managed as part of
the profile system with "system", and everything else should work fine.
=> Make "up" ignore "system" containers, rather than "non-default-boot"

bay/containers/container.py, bay/containers/formation.py, bay/plugins/volume.py
Two slightly expensive operations happening here: 
* I need to introspect the formation in order to get the running container instance name.
* I need to get the mount path of the volume_name, and there is probably a better way than to reverse-map in the existing dict.
This currently errors out if the given container is not running, or the volume is not mounted.
=> Command to copy a local file to a mounted volume on a container

bay/cli/__init__.py, bay/containers/container.py, bay/containers/graph.py, bay/containers/profile.py, bay/docker/runner.py, bay/plugins/profile.py
Firstly, this allows profiles to inherit from each other, so that we can define a few base profiles and have team-specific profiles inherit from those and keep up to date with changes. This is done by using the `inherits` key in a profile, like so:
```
inherits: tiny
containers:
core-web:
links:
optional:
- mysql-structured-content
```
This will allow people to replace their old `.tug.yaml` files with a `personal-foobar.yaml` file in the profiles directory, inheriting as appropriate (and gitignored)
Secondly, it changes the links keys from `ignore_links`, `links` and `extra_links` in various different meanings to a consistent `links` dictionary with `optional` and `required` sub-keys. The old versions still work for now for compatability.
=> Rework profiles to inherit and correctly handle links

bay/containers/profile.py
This fixes the error that was occuring after containers were injected into a profile during `bay mount`.
=> Don't error when "links" is missing from profile details

bay/containers/profile.py
This fixes the problem where a fresh installation tries to get the name from a path of `None`
=> Only decode profile name if one is set

bay/containers/profile.py
This allows a profile inheriting from another to override `default_boot`
to be `False` and have the change stick; previously, just listing the
container was enough to irrevocably set it to `True`.
=> Allow child profiles to override the default-boot of their parents

bay/docker/hosts.py, bay/docker/runner.py
This enables Docker For Mac caching on a host-by-host basis, if that host appears to be a local, Mac OS host with a unix-based socket connection.
=> Docker-for-Mac caching

bay/containers/container.py
The most recent release of attrs removed `__hash__` as existing by default in a rare breaking change.
=> Ensure Container has __hash__ with attrs 17.1

bay/docker/hosts.py, bay/plugins/volume.py, setup.py
This is quite a jump, but these were the only changes that affected us I could pull out of the changlog (I refrained from using the new prune methods for garbage collection as we need to support API 1.24)
=> Upgrade bay to docker python binding 2.3

bay/cli/tasks.py, bay/plugins/build.py
This makes it more obvious when it completes. Also fixes build to say
it's completed.
=> Print top-level tasks with their main line at the bottom

bay/plugins/volume.py
When using incompatible API Version, fixes the error of:
`docker.errors.InvalidVersion: force removal was introduced in API 1.25`
=> Remove force=True when destroying a volume

bay/constants.py, bay/plugins/build.py, bay/plugins/build_volumes.py
The goal is to automatically build and extract volumes when building containers that require them. In order to avoid extracting volumes that have not changed, we also want to prevent extracting a volume if the hash of its providing container has not changed. 
Adds a new hook called `PRE_GROUP_BUILD` that triggers before building a container and its ancestors. The only consumer of this hook is `BuildVolumesPlugin.pre_group_build`, which builds any provided volumes that are required by the containers about to be built.
Also updated `BuildVolumesPlugin.post_build` to only extract volumes that need to be extracted. It now caches the ID of the volume provider in the volume labels when creating the volume. After building a volume provider, it checks to see if the new ID differs from the cached …
=> Pre-build volume providers when building containers

bay/cli/__init__.py, bay/docker/hosts.py
Fix for tracebacks like 
```Traceback (most recent call last):
File "/Users/_____/.virtualenvs/bay/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 385, in _make_request
httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'
During handling of the above exception, another exception occurred:
[...]
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='192.168.90.100', port=2376): Read timed out. (read timeout=10)```
=> Increasing DockerAPI timeout to 42s, catching ReadTimeout exception

bay/containers/formation.py, bay/plugins/build_volumes.py, bay/plugins/volume.py
Makes the `volume destroy` command check the current configuration for instances that are using the named volume. If any instances are found, it fails with a helpful error message including a list of the conflicting instances.
Also updated the volume build plugin to use the new methods on `ContainerFormation` to find and remove instances that are using the volume.
=> Make `volume destroy` fail with a nice error message if instances are using the volume

bay/docker/images.py, bay/plugins/volume.py, bay/plugins/waits.py
HTTPS waits have the option not to check CA certs, and default to not checking them. If `verify_cert` is `True`, then it will check the cert against the certs loaded by the SSL library, but will not check the hostname (because the hostname is probably never going to be correct anyway).
Changes the behavior of the wait plugin slightly, so that any exception that bubbles up from a wait instance causes the plugin to fail with a pretty error, rather than printing the whole traceback.
=> HTTPS wait optionally checks CA certs, and fails helpfully

bay/plugins/build_volumes.py
There is a bug where volumes created using an old version of bay have `"Labels"` set to `None`, causing an error. This is the fix.
=> Account for the fact that "Labels" can be None

bay/plugins/build_volumes.py
The `BuildVolumesPlugin.post_build` method removes any volumes that are out of date and need to be recreated. However, it needs to make sure that there are no stopped containers that have the volume mounted, otherwise Docker will throw an exception. This simply adds a gc step to `post_build` before (re)creating the volume.
=> Prune containers before trying to remove volumes

bay/constants.py, bay/docker/build.py, bay/plugins/base.py, bay/plugins/build.py, bay/plugins/system.py, setup.py
Updated the `build` command to include system containers in `build profile`. Added a new plugin hook, `POST_GROUP_BUILD`, and a new plugin `SystemContainerBuildPlugin` that restarts outdated system containers after the build finishes.
=> Automatically rebuild system containers along with profile, and restart them when they change

bay/plugins/system.py
I didn't realize that `get_container_instance` can raise a `ValueError`. Just catch and continue.
=> Fix ValueError when a system container is not running

bay/plugins/tail.py
Add an option to limit the number of lines printed. If using `-f`, this limits the number of lines initially printed, but the output will still follow the log as normal. If the option is omitted, it prints the whole log as before.
`bay tail core-web` --> prints the whole `core-web` log, as before
`bay tail core-web 20` --> prints the last 20 lines of the `core-web` log
`bay tail core-web 20 -f` --> prints the last 20 lines of the `core-web` log, and continues printing any lines that are added subsequently
=> Add an argument to bay tail specifying the number of lines to print

bay/containers/container.py, bay/containers/formation.py, bay/containers/profile.py, bay/docker/runner.py
Add the option to specify a memory limit for containers using the `"mem_limit"` key in the container or profile YAML file.
The limit may be specified as either a number of bytes (float or int) or as a string in the format described in the [Docker docs](https://docs.docker.com/engine/admin/resource_constraints/#limit-a-containers-access-to-memory). Fortunately, if you specify an invalid value, Docker will raise a helpful exception explaining the format.
While I was in `profile.py`, I changed a bunch of single quotes to double quotes as well.
=> Add memory limit option to container and profile configuration

bay/containers/graph.py, bay/docker/introspect.py
Previously, when a running Bay container had its configuration removed or renamed, subsequent invocations of Bay would throw an exception when trying to introspect the unknown container. Consequently, every command would fail with an exception and nothing could be done until the user stopped the container manually.
Updated the introspector so that `add_container` only raises a warning in this case. Leaves `introspect_single_container`'s behavior unchanged, since this is only called when starting containers and should throw an exception if a configuration is missing.
As a bonus, I added a more helpful exception when Bay tries to link a container for which it has no configuration.
=> Fix exception when trying to introspect a running container with no configuration

bay/containers/container.py, bay/containers/formation.py, bay/containers/volumes.py, bay/docker/runner.py, bay/plugins/build.py, bay/plugins/container.py
In order to make volumes more adaptable for different use cases, I've added some basic configuration options. 
Now, volumes can be specified as dictionaries with settings. There are only a few valid settings, depending on the volume type:
- All volume types have a `source`, which behaves just like the string specifier. It is required.
- All volume types have a `mode`, which is a Docker volume mode (e.g. `"rw"` for read/write or `"ro"` for read-only). It defaults to `"rw"`.
- Bound volumes have a `required` option. If this is `False`, Bay will not fail when the source directory for the volume does not exist, and will run the container without the bind mount. It defaults to `True`.
Volumes can still be specified using just a string, which corresponds to the `source` option.
=> Add configuration options for volumes

bay/docker/runner.py
If you specified "cached" in the volume mode and the host supports cached volumes, it will be duplicated, causing an error.
=> Fix an error where "cached" appears more than once in the volume mode

bay/plugins/volume.py
It was incorrectly comparing objects to source names/strings.
=> Fix "bay volume list" command

bay/docker/introspect.py, bay/docker/runner.py, bay/exceptions.py, bay/plugins/waits.py
The issue: When a container fails on run, a nice message is printed to the terminal regarding the containers failure, but what would be REALLY nice is to see the tail of the container that failed as well. 
Solution provided here, grab the tail output from the offending container and append it to the error message to ensure it always gets written to the terminal.
=> add tail log to message

bay/docker/build.py
For long-running build steps, with long output, some data segments
of the build steps will be incomplete. This handle these cases by trying to
append subsequent segments until the a complete JSON data is found.
=> Build should handle incomplete data segments

data/completion/_bay, setup.py
This adds zsh completions under data/completion/_bay, and installs them using the [data_files](https://packaging.python.org/tutorials/distributing-packages/#data-files) kwarg to the `setup` function.
The zsh completions are installed into a /usr/local/share, which seems to be included in the zsh `$fpath` by default, and doesn't require root priveleges to write to.
The zsh completions included are
* first argument to `bay` - completes a list of commands w/ descriptions
* included plugins accepting a container as an argument - completes a list of containers by caching the output of `bay container`
* `bay profile` - completes a list of profiles by caching the output of `bay list_profiles`
All completions are cached for 1 day. Even though this means they won't always be fresh (user adds a …
=> Issue 113: Install zsh completions with bay package

bay/plugins/profile.py
Log the profile name when doing a `bay up`
=> EB-69876 Log the current profile name when doing a bay up

bay/containers/container.py, bay/docker/runner.py, docs/usage.rst
This solves the ability to mount images when the Docker daemon sees
the filesystem differently to the Bay client (e.g. when you are running
Docker For Windows from a WSL shell)
=> Add BAY_VOLUME_HOME for filesystem separation

bay/containers/container.py
Current code allows the specification of volumes from github repositories only if those repositories are under the "eventbrite" organization name.  This change allows any github repository to be used as the basis of a volume.
=> Allow non-eventbrite github volumes

bay/docker/hosts.py
Summary:
The host DNS changed in Docker 18.03, and is now the same for Docker for Mac and Docker for Windows: https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-18030-ce-mac59-2018-03-26
The old DNS are deprecated.
Test Plan: `bay build ssh-agent`, then `bay shell core` and `echo $SSH_AUTH_HOST` should return `host.docker.internal` if you are at least on Docker 18.03.
Reviewers: venkatesh, aravind
Differential Revision: https://phabricator.evbhome.com/D56453
=> Change Docker host DNS

bay/docker/hosts.py
Unfortunately, `host.docker.internal` is provided by Docker for Mac and Docker for Windows, so this stops it breaking under Linux.
=> Fix the docker.internal hostname to only trigger on OSX/Windows

docs/usage.rst
```
➜  ~ bay list-profiles
Usage: bay [OPTIONS] COMMAND [ARGS]...
Error: No such command "list-profiles", are you trying to run: list_profiles?
```
=> Fix list_profiles command in docs

CHANGELOG.txt, bay/docker/images.py, bay/version.py
I was trying to reproduce the issue by altering my tokens (okta, aws and docker creds) but could not get to in a state where authentication was wrong and docker api returned "Not Found".
When forcing docker credentials to be altered at run-time, I would get an error "Too many failures while pulling".
I ended up bumping an image tag to simulate a "Not Found" error.
This fix would address the issue that we have seen.
To give the ability for users to force local build, they can set an environment variable.
Scenario 1: user get's not found error, bay exits and asks user to login to registry.
```
$ bay build             
Pulling remote image eventbrite/cassandra-core:1.0.3: 
Building: 
Cannot pull image 671197494237.dkr.ecr.us-east-1.amazonaws.com/docker-dev/eventbrite/cassandra-core:1.0.3.
To …
```
=> EB-77208 Ask user to run bay registry login in case of docker pull not found error.

bay/docker/images.py
This optimization was measured with profile tidy, it saves approximately 30 sec when doing `bay build`.
The time saved would be even more important when running outside of the US.
=> EB-69437 Bay shouldn't pull a versioned image that is already present

bay/plugins/build.py
**Summary:**
Currently if a profile defined 'ignore-dependencies: true' and 'inherits: base', when doing `bay build`, it only builds the containers listed in the profile file, not the parent (in this example the 'base' profile). The workaround for the user is to switch profile, build and re-switch profile.
With this fix, the build will include the container listed in the ancestor profile as well, so the user doesn't need to switch profile when building.
**Test Plan:**
tested with the profile base-cerberus. `bay build` and `bay up`.
=> EB-84956 when building a profile with the 'inherits' property, include the parent containers in the build

CHANGELOG.txt, bay/docker/build.py, bay/version.py
Preventing setting the file date to zero when creating the docker image.
Use the same date as the file system file.
- for src file only
- under a feature flag
=> EB-90124 when building docker images do not reset file time to 0

CHANGELOG.txt, bay/docker/runner.py, bay/version.py
Docker's `binds` argument (defined here as `volume_binds`) can be in two formats. It can be in a list of strings `'{source}:{destination}:{mode}'`, or it can be a dict whose keys are sources and whose values are a dict of `{'bind': '{destination}', 'mode': '{mode}'}`. If you specify `binds` in dict format, the Docker SDK converts it to list format before sending it to the Docker process. However, the dict format limits you to one container mountpoint per host source. Docker permits multiple container mountpoints per host source, and the only way to specify that is with the list format. Previously we used the dict format, but this change switches to the list format to support multiple mountpoints.
=> Use list format for binds instead of dict format for multiple mountpoints

bay/docker/images.py, bay/plugins/attach.py, bay/plugins/run.py
This adds a simple, optional `--shell` parameter to `bay shell` and `bay attach` that permits the user to override the default `/bin/bash` with something else, such as `/bin/sh`. This is especially critical for certain lightweight containers that completely lack Bash. This also fixes a few Flake8 issues that were making this build fail.
=> Permit use of shell other than default /bin/bash

CHANGELOG.txt, bay/version.py
Changelog Details:
- [MINOR] Add support for invoke release
- [PATCH] Migrate `convert` to `converter`
- Permit use of shell other than default /bin/bash
- Fix RELEASE doc
=> Released Bay version 2.19.0
